#include <stdio.h>
#include <iostream.h>
#include <conio.h>
#include <math.h>
#include <stdlib.h>
#include <string.h>
#include <fstream.h>

void main()
{

srand(time(NULL));
int a[4]={1,2,3,4},b[4]={1,2,3,4}, c[4]={1,2,3,4},d[4]={1,2,3,4},e[4]={1,2,3,4};
int a1[10]={1,2,3,4,5,6,7,8,9,10};
int a2[10]={1,2,3,4,5,6,7,8,9,10};
int a3[10]={1,2,3,4,5,6,7,8,9,10};
int a4[10]={1,2,3,4,5,6,7,8,9,10};
int a5[10]={1,2,3,4,5,6,7,8,9,10};
int a6[10]={1,2,3,4,5,6,7,8,9,10};
int a7[10]={1,2,3,4,5,6,7,8,9,10};
int a8[10]={1,2,3,4,5,6,7,8,9,10};
int a9[10]={1,2,3,4,5,6,7,8,9,10};
int a10[10]={1,2,3,4,5,6,7,8,9,10};
int a11[10]={1,2,3,4,5,6,7,8,9,10};
int a12[10]={1,2,3,4,5,6,7,8,9,10};
int a13[10]={1,2,3,4,5,6,7,8,9,10};
int a14[10]={1,2,3,4,5,6,7,8,9,10};
int a15[10]={1,2,3,4,5,6,7,8,9,10};
int a16[10]={1,2,3,4,5,6,7,8,9,10};
int a17[10]={1,2,3,4,5,6,7,8,9,10};
int a18[10]={1,2,3,4,5,6,7,8,9,10};
int a19[10]={1,2,3,4,5,6,7,8,9,10};
int a20[10]={1,2,3,4,5,6,7,8,9,10};
int r,i,j ;
for (i=10;i>0;i--)
{
	r=rand()%i  ;
	cout<<a1[r]<<" ";
	while(r<i-1)
	{
		a1[r]=a1[r+1];
		r++;
   }
}
cout<<" ";
for (i=10;i>0;i--)
{
	r=rand()%i  ;
	cout<<a2[r]<<" ";
	while(r<i-1)
	{
		a2[r]=a2[r+1];
		r++;
   }
}
cout<<" ";
for (i=10;i>0;i--)
{
	r=rand()%i  ;
	cout<<a3[r]<<" ";
	while(r<i-1)
	{
		a3[r]=a3[r+1];
		r++;
   }
}
cout<<" ";
for (i=10;i>0;i--)
{
	r=rand()%i  ;
	cout<<a4[r]<<" ";
	while(r<i-1)
	{
		a4[r]=a4[r+1];
		r++;
   }
}
cout<<" ";
for (i=10;i>0;i--)
{
	r=rand()%i  ;
	cout<<a5[r]<<" ";
	while(r<i-1)
	{
		a5[r]=a5[r+1];
		r++;
   }
}
cout<<" ";
for (i=10;i>0;i--)
{
	r=rand()%i  ;
	cout<<a6[r]<<" ";
	while(r<i-1)
	{
		a6[r]=a6[r+1];
		r++;
   }
}
cout<<" ";
for (i=10;i>0;i--)
{
	r=rand()%i  ;
	cout<<a7[r]<<" ";
	while(r<i-1)
	{
		a7[r]=a7[r+1];
		r++;
   }
}
cout<<" ";
for (i=10;i>0;i--)
{
	r=rand()%i  ;
	cout<<a8[r]<<" ";
	while(r<i-1)
	{
		a8[r]=a8[r+1];
		r++;
   }
}
cout<<" ";
for (i=10;i>0;i--)
{
	r=rand()%i  ;
	cout<<a9[r]<<" ";
	while(r<i-1)
	{
		a9[r]=a9[r+1];
		r++;
   }
}
cout<<" ";
for (i=10;i>0;i--)
{
	r=rand()%i  ;
	cout<<a10[r]<<" ";
	while(r<i-1)
	{
		a10[r]=a10[r+1];
		r++;
   }
}
cout<<" ";
for (i=10;i>0;i--)
{
	r=rand()%i  ;
	cout<<a11[r]<<" ";
	while(r<i-1)
	{
		a11[r]=a11[r+1];
		r++;
   }
}
cout<<" ";
for (i=10;i>0;i--)
{
	r=rand()%i  ;
	cout<<a12[r]<<" ";
	while(r<i-1)
	{
		a12[r]=a12[r+1];
		r++;
   }
}
cout<<" ";
for (i=10;i>0;i--)
{
	r=rand()%i  ;
	cout<<a13[r]<<" ";
	while(r<i-1)
	{
		a13[r]=a13[r+1];
		r++;
   }
}
cout<<" ";
for (i=10;i>0;i--)
{
	r=rand()%i  ;
	cout<<a14[r]<<" ";
	while(r<i-1)
	{
		a14[r]=a14[r+1];
		r++;
   }
}
cout<<" ";
for (i=10;i>0;i--)
{
	r=rand()%i  ;
	cout<<a15[r]<<" ";
	while(r<i-1)
	{
		a15[r]=a15[r+1];
		r++;
   }
}
cout<<" ";
for (i=10;i>0;i--)
{
	r=rand()%i  ;
	cout<<a16[r]<<" ";
	while(r<i-1)
	{
		a16[r]=a16[r+1];
		r++;
   }
}
cout<<" ";
for (i=10;i>0;i--)
{
	r=rand()%i  ;
	cout<<a17[r]<<" ";
	while(r<i-1)
	{
		a17[r]=a17[r+1];
		r++;
   }
}
cout<<" ";
for (i=10;i>0;i--)
{
	r=rand()%i  ;
	cout<<a18[r]<<" ";
	while(r<i-1)
	{
		a18[r]=a18[r+1];
		r++;
   }
}
cout<<" ";
for (i=10;i>0;i--)
{
	r=rand()%i  ;
	cout<<a19[r]<<" ";
	while(r<i-1)
	{
		a19[r]=a19[r+1];
		r++;
   }
}
cout<<" ";
for (i=10;i>0;i--)
{
	r=rand()%i  ;
	cout<<a20[r]<<" ";
	while(r<i-1)
	{
		a20[r]=a20[r+1];
		r++;
   }
}
cout<<" ";
getch();
}